# Site
name: "Conferts Haut-Barr"
title: "conferts"
description: "Les concerts des confin√©s de la rue du Haut-Barr"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ''
include: ["_pages"]
# permalink: /:title/
# google_analytics: 'UA-xxxxxxxx-1'
# disqus: 'confertshautbarr'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
email: jacko.kaiser@gmail.com

# Authors
authors:
  jacques:
    name: Jacques
    display_name: Jacques
    gravatar:
    email: jacko.kaiser@gmail.com
    web: https://jacqueskaiser.com
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-compress-images

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true


# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
